v_box = QVBoxLayout()
v_box3 = QVBoxLayout()
v_box4 = QVBoxLayout()
v_box5 = QVBoxLayout()
v_box6 = QVBoxLayout()
v_box7 = QVBoxLayout()
v_box2 = QVBoxLayout()

v_box.addWidget(self.yazi_alanidolar)
v_box3.addWidget(self.yazi_alanieuro)
v_box4.addWidget(self.yazi_alanibist)
v_box5.addWidget(self.yazi_alanisterlin)
v_box6.addWidget(self.yazi_alanibtc)
v_box7.addWidget(self.yazi_alanigumus)

v_box.addWidget(self.dolar)
v_box3.addWidget(self.euro)
v_box4.addWidget(self.bist)
v_box5.addWidget(self.sterlin)
v_box6.addWidget(self.btc)
v_box7.addWidget(self.gumus)

h_box = QHBoxLayout()
h_box2 = QHBoxLayout()
h_box3 = QHBoxLayout()
h_box4 = QHBoxLayout()
h_box5 = QHBoxLayout()
h_box6 = QHBoxLayout()

h_box.addWidget(self.sayialanidolar)
h_box.addStretch()
h_box.addLayout(v_box)
h_box.addStretch()
h_box.addLayout(v_box)

h_box2.addWidget(self.sayialanieuro)
h_box2.addStretch()
h_box2.addLayout(v_box3)
h_box2.addStretch()
h_box2.addLayout(v_box3)

h_box3.addWidget(self.sayialanibist)
h_box3.addStretch()
h_box3.addLayout(v_box4)
h_box3.addStretch()
h_box3.addLayout(v_box4)

h_box4.addWidget(self.sayialanisterlin)
h_box4.addStretch()
h_box4.addLayout(v_box5)
h_box4.addStretch()
h_box4.addLayout(v_box5)

h_box5.addWidget(self.sayialanibtc)
h_box5.addStretch()
h_box5.addLayout(v_box6)
h_box5.addStretch()
h_box5.addLayout(v_box6)

h_box6.addStretch()
h_box6.addWidget(self.sayialanigumus)
h_box6.addStretch()
h_box6.addLayout(v_box7)
h_box6.addStretch()
h_box6.addLayout(v_box7)

self.setLayout(h_box)
self.setLayout(h_box2)
self.setLayout(h_box3)
self.setLayout(h_box4)
self.setLayout(h_box5)
self.setLayout(h_box6)